spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  mobile:
    devicedelegatingviewresolver:
      enabled: true
      normal-prefix: normal/
      mobile-prefix: mobile/
      tablet-prefix: mobile/
logging:
  config: classpath:log4j2.xml
debug: false
file:
  templateLocation: classpath:/templates/
  staticLocation: classpath:/static/
  resourceUri: /fileUpload/**
  resourceLocation: D:/fileUpload/**
  excelPath: D:/fileUpload/excel
mybatis:
  mapper-locations: classpath:/mybatis/*.xml

hibernate:
  metadata_builder_contributor=com:
    vladmihalcea:
      book:
        hpjp:
          SqlFunctionsMetadataBuilderContributor:#server:
#  ssl:
#    key-store: classpath:teraenergy.p12
#    key-store-type: PKCS12
#    key-store-password: teraenergy
#    key-alias: teraenergy
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://192.168.0.53:3306/illegal_parking?serverTimezone=Asia/Seoul
    username: root
    password: tera
    hikari:
      connection-timeout: 30000 # connection_timeout
      max-lifetime: 1800000 # wait_timeout
server:
  port: 8090
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# home
spring:
  config:
    activate:
      on-profile: home
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://localhost:3306/illegal_parking?serverTimezone=Asia/Seoul
    username: wooyoung
    password: rudnf12dnjf
    hikari:
      connection-timeout: 30000 # connection_timeout
      max-lifetime: 1800000 # wait_timeout
      maximum-pool-size: 30
server:
  port: 8090
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# release
spring:
  config:
    activate:
      on-profile: release
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://192.168.0.53:3306/illegal_parking?serverTimezone=Asia/Seoul
    username: tera
    password:
    hikari:
      connection-timeout: 30000 # connection_timeout
      max-lifetime: 1800000 # wait_timeout
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m